### ISSUE TITLE
Build a PDF for us, please

### ISSUE THREAD

**Issue by bryanshaw46** [erikogan/madness_cards#1]
I would appreciate it if you would build the PDF for us and placed it on Out of the Abyss facebook group.

**Comment by erikogan** [comment]
Thanks for your interest! You can download a PDF from [the original blog post](https://stealthymonkeys.com/2018/05/madness-cards-for-out-of-the-abyss), but I also did exactly what you are requesting when I [announced the project back in May](https://www.facebook.com/groups/460200827491996/932515630260511/). The files section of the group is full of handy stuff, but it can be hard to find particular items.

**Comment by erikogan** [comment]
[The original blog post](https://stealthymonkeys.com/2018/05/madness-cards-for-out-of-the-abyss) also has a link to a tarball full of 300dpi PNG files, which might also be easier to use.
